version: '3'

networks:
  backend:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    environment: ["bootstrap.memory_lock=true", "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"]
    volumes: ["./data/es:/usr/share/elasticsearch/data"]
    networks: [backend]
    expose: ["9200"]
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0
    networks: [backend]
    ports: ["5601:5601"]
    expose: ["5601"]
  redis:
    image: redis
    command: ["--appendonly yes"]
    volumes: ["./data/redis:/data"]
    networks: [backend]
    expose: ["6379"]
  vautour:
    build: .
    command: -log-level=debug
    volumes: ["./config:/config"]
    networks: [backend]
    restart: always