[[constraint]]
  name = "github.com/coreos/pkg"
  version = "4.0.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.15.2"

[[constraint]]
  name = "github.com/hillu/go-yara"
  version = "1.1.0"

[[constraint]]
  name = "github.com/olivere/elastic"
  version = "6.2.17"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/kataras/go-mailer"
  version = "0.1.0"
